apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin-service:latest
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command: ["/bin/bash", "-c", "pgrep telegraf && pgrep nginx && pgrep php-fpm7"]
          initialDelaySeconds: 10
          periodSeconds: 5
        ports:
        - containerPort: 5000
          name: phpmyadmin

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
    - name: phpmyadmin
      protocol: TCP
      port: 5000
      targetPort: 5000
