apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress-service:latest
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command: ["/bin/bash", "-c", "pgrep telegraf && pgrep php-fpm7 && pgrep nginx"]
          initialDelaySeconds: 10
          periodSeconds: 5
        ports:
        - containerPort: 5050
          name: wordpress

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  name: wordpress-service
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
    - name: wordpress
      protocol: TCP
      port: 5050
      targetPort: 5050
