apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-service:latest
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command: ["/bin/bash", "-c", "pgrep telegraf && pgrep vsftpd"]
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
          - name: USER
            value: user
          - name: PASSWORD
            value: pass
        ports:
          - containerPort: 21
            name: ftps-control
          - containerPort: 20
            name: ftps-data
          - containerPort: 21000
            name: ftps-opasv-min
          - containerPort: 21001 
            name: ftps-opasv-max

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  name: ftps-service
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
  - port: 21
    name: ftps-control
    targetPort: 21
    protocol: TCP
  - port: 20
    name: ftps-data
    targetPort: 20
    protocol: TCP
  - port: 21000
    name: ftps-opasv-min
    targetPort: 21000
    protocol: TCP
  - port: 21001
    name: ftps-opasv-max
    targetPort: 21001
    protocol: TCP
