apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: service_ftps:latest
        imagePullPolicy: Never
        env:
          - name: USER
            value: user
          - name: PASSWORD
            value: ftpspass
        ports:
          - containerPort: 20
            name: ftps_control
          - containerPort: 21
            name: ftps_data
          - containerPort: 21000
            name: ftps_opasv_min_port
          - containerPort: 21001 
            name: ftps_opasv_max_port

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  name: ftps-service
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
  - port: 20
    name: ftps_control
    targetPort: 20
    protocol: TCP
  - port: 21
    name: ftps_data
    targetPort: 21
    protocol: TCP
  - port: 21000
    name: ftps_opasv_min_port
    targetPort: 21000
    protocol: TCP
  - port: 21001
    name: ftps_opasv_max_port
    targetPort: 21001
    protocol: TCP
